---
title: "Google restaurant reviews in Kuala Lumpur, Petaling Jaya and Shah Alam, Malaysia"
subtitle: "Part two"
author: "AIMdata"
execute: 
  echo: false
---


```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(scales)
library(tidytext)
library(widyr)
library(ggraph)
library(patchwork)
library(kableExtra)
library(fuzzyjoin)
library(viridis)
library(textdata)
library(stringr)

`%out%` <- Negate(`%in%`)
options(scipen = 100)
theme_set(theme_light())
range_wna <- function(x){(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))}

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```


```{r data}

trip_kl_cuisine <- read_csv("./data/trip_kl_cuisine.csv")

google_kl_cuisine <- read_csv("./data/google_kl_cuisine.csv")

```

```{r words}

google_rating_words <- google_kl_cuisine |> 
  select(rowid, rating, review) |> 
  unnest_tokens(word, review) |> 
  # mutate(word = SnowballC::wordStem(word, language = "porter")) |> 
  anti_join(stop_words, by = "word") |>
  add_count(word) 

trip_rating_words <- trip_kl_cuisine |> 
  select(rowid, review, rating) |> 
  unnest_tokens(word, review) |> 
  # mutate(word = SnowballC::wordStem(word, language = "porter")) |> 
  anti_join(stop_words, by = "word") |>
  add_count(word) 

  bind_tf_idf(rating, word, n) |> 
  tidylo::bind_log_odds(rating, word, n)
```

Sentiment analysis to see if the exceptional five-star reviews can be separated out. 

```{r}

negative_nrc <- get_sentiments("nrc") |> 
  filter(sentiment %in% c("disgust", "fear", "anger", 
                          "negative", "sadness"))

nrc <- get_sentiments("nrc")

google_rating_words |> 
  inner_join(get_sentiments("afinn")) |> 
  group_by(rowid, rating) |> 
  summarise(sentiment = mean(value, na.rm = TRUE), 
            .groups = "drop") |> 
  ggplot(aes(x = sentiment)) + 
  geom_histogram() + 
  facet_wrap(~ rating, scales = "free")
  

```

Maybe redo this to make a count of reviews with each sentiment? 

```{r}
google_rating_words |> 
  inner_join(get_sentiments("nrc")) |> 
  group_by(sentiment, rating, rowid) |> 
  summarise(count = n_distinct(word), 
            .groups = "drop") |> 
  group_by(rating, sentiment) |> 
  summarise(reviews = n_distinct(rowid), 
            .groups = "drop") |> 
  group_by(rating) |> 
  mutate(sum = sum(reviews), 
         pc = reviews / sum) |> 
  ungroup() |> 
  mutate(sentiment = fct_relevel(sentiment, 
                                 c("surprise",
                                   "anticipation", 
                                   "joy", 
                                   "trust", 
                                   "positive", 
                                   "negative", 
                                   "sadness",
                                   "fear", 
                                   "anger", 
                                   "disgust"))) |> 
  ggplot(aes(x = pc, y = fct_rev(sentiment))) + 
  geom_col(aes(fill = sentiment)) + 
  scale_fill_manual(
    values =c(
      "anger" = "#780000", 
      "disgust" = "#c1121f", 
      "fear" = "#9e2a2b", 
      "negative" = "#bc4749", 
      "sadness" = "#b56576", 
      "anticipation" = "#90e0ef", 
      "joy" = "#00b4d8", 
      "surprise" = "#caf0f8", 
      "positive" = "#0077b6", 
      "trust" = "#118ab2"
    )
  ) +
  facet_wrap(~rating, scales = "free") + 
  scale_x_continuous(labels = percent) +
  guides(fill = "none") + 
  theme(strip.background = element_rect(fill = "black")) + 
  labs(title = "Breakdown of NRC sentiments in Google reviews by rating", 
       subtitle = "In the Klang Valley.", 
       y = "", 
       x = "")
  

```

What is the point of five-star reviews if 5% of them express disgust?

```{r}
trip_rating_words |> 
  inner_join(get_sentiments("nrc")) |> 
  group_by(sentiment, rating, rowid) |> 
  summarise(count = n_distinct(word), 
            .groups = "drop") |> 
  group_by(rating, sentiment) |> 
  summarise(reviews = n_distinct(rowid), 
            .groups = "drop") |> 
  group_by(rating) |> 
  mutate(sum = sum(reviews), 
         pc = reviews / sum) |> 
  ungroup() |> 
  mutate(sentiment = fct_relevel(sentiment, 
                                 c("surprise",
                                   "anticipation", 
                                   "joy", 
                                   "trust", 
                                   "positive", 
                                   "negative", 
                                   "sadness",
                                   "fear", 
                                   "anger", 
                                   "disgust"))) |> 
  ggplot(aes(x = pc, y = fct_rev(sentiment))) + 
  geom_col(aes(fill = sentiment)) + 
  scale_fill_manual(
    values =c(
      "anger" = "#780000", 
      "disgust" = "#c1121f", 
      "fear" = "#9e2a2b", 
      "negative" = "#bc4749", 
      "sadness" = "#b56576", 
      "anticipation" = "#90e0ef", 
      "joy" = "#00b4d8", 
      "surprise" = "#caf0f8", 
      "positive" = "#0077b6", 
      "trust" = "#118ab2"
    )
  ) +
  facet_wrap(~rating, scales = "free") + 
  scale_x_continuous(labels = percent) +
  guides(fill = "none") + 
  theme(strip.background = element_rect(fill = "black")) + 
  labs(title = "Breakdown of NRC sentiments in Trip Advisor reviews by rating", 
       subtitle = "In the Klang Valley.", 
       y = "", 
       x = "")
  
```



```{r fig.height=7}
trip_rating_words |> 
  filter(n >= 20) |> 
  filter(word %out% c("monk3yseendo")) |> 
  arrange(desc(log_odds_weighted)) |> 
  group_by(rating) |> 
  slice(1:20) |>
  ggplot(aes(x = log_odds_weighted, 
             y = reorder_within(str_sub(word, 1, 25), 
                                log_odds_weighted, 
                                rating))) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ rating, scales = "free")
```

```{r fig.height=7}
google_rating_words |> 
  filter(n >= 20) |>  
  arrange(desc(log_odds_weighted)) |> 
  group_by(rating) |> 
  slice(1:20) |>
  ggplot(aes(x = log_odds_weighted, 
             y = reorder_within(str_sub(word, 1, 25), 
                                log_odds_weighted, 
                                rating))) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ rating, scales = "free")
```

```{r fig.height=7}
trip_rating_words |> 
  filter(n >= 20) |>  
  filter(word %out% c("forward.packaging", "lunch.the")) |> 
  arrange(desc(tf_idf)) |> 
  group_by(rating) |> 
  slice(1:20) |>
  ggplot(aes(x = tf_idf, 
             y = reorder_within(str_sub(word, 1, 25), 
                                tf_idf, 
                                rating))) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ rating, scales = "free")
```

```{r fig.height=7}
google_rating_words |>
  filter(n >= 10) |> 
  filter(word %out% c("shawn", "sohag", "rafat", "md", "anik", "nero", "makhani", 
                      "mir", "ak", "kl", "belal", "lauk", "marcus", "omar", "halah", 
                      "zahangir")) |> 
  arrange(desc(tf_idf)) |> 
  group_by(rating) |> 
  slice(1:20) |>
  ggplot(aes(x = tf_idf, 
             y = reorder_within(str_sub(word, 1, 25), 
                                tf_idf, 
                                rating))) + 
  geom_col() + 
  scale_y_reordered() + 
  facet_wrap(~ rating, scales = "free")
```

```{r}
google_rating_words |> 
  count(n) |> 
  arrange(desc(nn)) |> 
```

## One-star reviews

## Five-star reviews

I think you have to use bigrams, 


```{r}
trip_5_star_network <- trip_rating_words |> 
  filter(rating == 5 & n > 100) |> 
  pairwise_cor(word, rowid, sort = TRUE) |> 
  left_join(
    trip_rating_words |>
      filter(rating == 5 & n > 100) |>
      pairwise_count(word, rowid, sort = TRUE), 
    by = c("item1", "item2")
  ) |> 
  filter(correlation > .2) |> 
  igraph::graph_from_data_frame() |> 
  ggraph(layout = "fr") + 
  geom_edge_link(aes(alpha = correlation, edge_width = n), colour = "#457b9d", check_overlap = TRUE) +
  scale_edge_width_continuous(range = c(.1, 2.5), trans = "log10") +
  scale_alpha_continuous(range = c(0.01, 0.08)) +
  geom_node_point(colour = "#457b9d", alpha = 0.2, size = .5) +
  # geom_node_text(aes(label = ifelse(name %in% 
  #                                       c("waited", "service", "experience", 
  #                                         "price", "quality", "fresh", 
  #                                         "tasted", "disappointing"),
  #                                     str_to_title(name),
  #                                     "")), 
  #                size = 3.5, 
  #                alpha = .9, 
  #                colour = "#00afb9", 
  #                fontface = "bold") +
  geom_node_text(aes(label = name), size = 3.1, alpha = .4, 
                 colour = "#caf0f8") + 
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = .5, colour = "#219ebc"), 
        panel.background = element_rect(fill = "#03071e"), 
        plot.background = element_rect(fill = "#1b263b"), 
        plot.title = element_text(colour = "#219ebc"), 
        plot.subtitle = element_text(colour = "#219ebc", size = 10)) + 
  labs(title = "Network graph of Five-star Reviews on Trip Advisor", 
       subtitle = "Line thickness indicates number of events involving those words, line transparency indicates the correlation between words. Key topics highlighted.", 
       caption = "Source: TripAdvisor.com; Ng Choon Khon")


ggsave(here("plots", "trip_5_star_network_graph.png"), 
       width = 10, height = 6.5, units = "in", dpi = 300)
    
```



```{r}
trip_5_star_network <- trip_kl_cuisine |> 
  mutate(review_id = row_number()) |> 
  filter( rating == 5) |> 
  unnest_tokens(word, review) |> 
  anti_join(stop_words) |> 
  filter(!str_detect(word, "'")) |> 
  filter(str_detect(word, "[a-z]")) |> 
  add_count(word) |> 
  filter(n > 30) |> 
  pairwise_cor(word, review_id, sort = TRUE) |> 
  filter(correlation >= .2) |> 
  left_join(
    trip_kl_cuisine |> 
      mutate(review_id = row_number()) |> 
      filter( rating == 5) |>
      unnest_tokens(word, review) |> 
      anti_join(stop_words) |> 
      filter(!str_detect(word, "'")) |>
      filter(str_detect(word, "[a-z]")) |>
      add_count(word) |> 
      filter(n > 13) |> 
      pairwise_count(word, review_id, sort = TRUE), 
    by = c("item1", "item2")
  ) |> 
  igraph::graph_from_data_frame() |> 
  ggraph(layout = "fr") + 
  geom_edge_link(aes(alpha = correlation, edge_width = n), colour = "#457b9d", check_overlap = TRUE) +
  scale_edge_width_continuous(range = c(.1, 2.5), trans = "log10") +
  scale_alpha_continuous(range = c(0.01, 0.08)) +
  geom_node_point(colour = "#457b9d", alpha = 0.2, size = .5) +
  # geom_node_text(aes(label = ifelse(name %in% 
  #                                       c("waited", "service", "experience", 
  #                                         "price", "quality", "fresh", 
  #                                         "tasted", "disappointing"),
  #                                     str_to_title(name),
  #                                     "")), 
  #                size = 3.5, 
  #                alpha = .9, 
  #                colour = "#00afb9", 
  #                fontface = "bold") +
  geom_node_text(aes(label = name), size = 3.1, alpha = .4, 
                 colour = "#caf0f8") + 
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = .5, colour = "#219ebc"), 
        panel.background = element_rect(fill = "#03071e"), 
        plot.background = element_rect(fill = "#1b263b"), 
        plot.title = element_text(colour = "#219ebc"), 
        plot.subtitle = element_text(colour = "#219ebc", size = 10)) + 
  labs(title = "Network graph of Five-star Reviews on Trip Advisor", 
       subtitle = "Line thickness indicates number of events involving those words, line transparency indicates the correlation between words. Key topics highlighted.", 
       caption = "Source: TripAdvisor.com; Ng Choon Khon")


ggsave(here("plots", "trip_5_star_network_graph.png"), 
       width = 10, height = 6.5, units = "in", dpi = 300)
```

